Repository parley-messaging/ios-library, pull requests merged in 2024-07, with the labels that each got.

#142 Remove ParleyRequestCancelable because it is not used + run http requests on background queue;
  README.md
  Sources/Parley/Data/Remotes/MessageRemoteService.swift
  Sources/Parley/Data/Remotes/ParleyNetworkSession.swift
  Sources/Parley/Data/Remotes/ParleyRemote.swift
  Sources/Parley/Data/Remotes/ParleyRequestCancelable.swift
  Sources/Parley/Extensions/DispatchQueue+Queue.swift
  Sources/ParleyNetwork/AlamofireNetworkSession.swift
  Sources/ParleyNetwork/Request+RequestCancable.swift
  Tests/ParleyTests/Data/Remotes/ParleyRemoteTests.swift
  Tests/ParleyTests/Data/Remotes/RequestCancelableStub.swift
  Tests/ParleyTests/TestDoubles/ParleyNetworkSessionSpy.swift
  Tests/ParleyTests/TestDoubles/QueueSpy.swift
Labels: enhancement

#144 Remove observers on config reset;
  Sources/Parley/Parley.swift
Labels: bug, ready

#149 Make a proposal to fix that fatalError is called when no error is set.
  Sources/Parley/Data/PollingService.swift
  Sources/Parley/Data/Remotes/ParleyRemote.swift
  Sources/Parley/Views/ParleyView.swift
  Tests/ParleyTests/Data/Remotes/ParleyRemoteTests.swift
Labels: enhancement, ready
