Repository parley-messaging/ios-library, pull requests merged in 2024-05, with the labels that each got.

#88 Prevent duplicate creation of classes
  Sources/Parley/Constants.swift
  Sources/Parley/Data/Models/Common/ParleyHTTPDataResponse.swift
  Sources/Parley/Data/Remotes/EventRemoteService.swift
  Sources/Parley/Data/Remotes/MessageRemoteService.swift
  Sources/Parley/Data/Remotes/ParleyHTTPDataResponse+decodeAtKeyPath.swift
  Sources/Parley/Data/Remotes/ParleyRemote.swift
  Sources/Parley/Data/Remotes/UserTypingEvent.swift
  Sources/Parley/Data/Repositories/ImageRepository.swift
  Sources/Parley/Data/Repositories/MessageRepository.swift
  Sources/Parley/Extensions/SymmetricKeyExtension.swift
  Sources/Parley/Extensions/UIViewExtension.swift
  Sources/Parley/Extensions/UImageExtension.swift
  Sources/Parley/Parley.swift
  Sources/Parley/PollingService.swift
  Sources/Parley/Presentation/Models/ImageDisplayModel.swift
  Sources/Parley/Views/ParleyView.swift
Labels: ready

#89 Implement dependabot to create pr's for swift package updates.
  .github/dependabot.yml
Labels: ready

#84 Make it possible to specify rounding for corners for image
  Sources/Parley/Views/ParleyImageView.swift
  Sources/Parley/Views/ParleyMessageView/ParleyMessageView.swift
  Sources/Parley/Views/ParleyMessageView/ParleyMessageViewAppearance.swift
Labels: enhancement

#85 feat: Make possible to always enable polling of new messages;
  Sources/Parley/Parley.swift
  Sources/Parley/Views/ParleyView.swift
Labels: enhancement

#90 Always call completion of set user information
  Sources/Parley/Parley.swift
Labels: ready

#92 fix: do not setup observers when parly is not configured;
  Sources/Parley/Parley.swift
Labels: ready

#100 Make sure the reachability is set
  Sources/Parley/Parley.swift
Labels: bug, ready

#94 Make registering of cells more type safe
  Sources/Parley/PollingService.swift
  Sources/Parley/Views/MessageImageViewController.swift
  Sources/Parley/Views/ParleySuggestionsView/ParleySuggestionsView.swift
  Sources/Parley/Views/ParleyView.swift
  Sources/Parley/Views/ReusableView.swift
  Sources/Parley/Views/TableViewCells/MessageTableViewCell/MessageTableViewCell.swift
Labels: enhancement, ready

#98 Add some screenshots for ParleyMessageView
  Package.resolved
  Package.swift
  Sources/Parley/Data/ImageLoader.swift
  Sources/Parley/Views/ParleyMessageView/ParleyMessageView.swift
  Sources/Parley/Views/ParleyMessageView/ParleyMessageView.xib
  Tests/ParleyTests/Media.xcassets/Contents.json
  Tests/ParleyTests/Media.xcassets/Parley.imageset/Contents.json
  Tests/ParleyTests/Media.xcassets/Parley.imageset/Parley.png
  Tests/ParleyTests/Media.xcassets/chat_bubble_agent.imageset/Contents.json
  Tests/ParleyTests/Media.xcassets/chat_bubble_agent.imageset/chat_bubble_user.pdf
  Tests/ParleyTests/Media.xcassets/chat_bubble_user.imageset/Contents.json
  Tests/ParleyTests/Media.xcassets/chat_bubble_user.imageset/chat_bubble_agent.pdf
  Tests/ParleyTests/ParleyMessageViewTests.swift
  Tests/ParleyTests/README.md
  Tests/ParleyTests/TestDoubles/ImageLoaderStub.swift
  Tests/ParleyTests/TestDoubles/Message+TestData.swift
  Tests/ParleyTests/TestTools/XCTest+Tools.swift
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testCustomBalloonImageUser.1.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testCustomBalloonImageUser.2.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testDefaultAgentMessageView.1.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testDefaultAgentMessageView.2.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testDefaultAgentMessageViewWithShortMessage.1.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testDefaultAgentMessageViewWithShortMessage.2.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testDefaultUserMessageView.1.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testDefaultUserMessageView.2.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testDefaultUserMessageViewFailedStatus.1.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testDefaultUserMessageViewFailedStatus.2.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testDefaultUserMessageViewPendingStatus.1.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testDefaultUserMessageViewPendingStatus.2.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testDefaultUserMessageViewWithShortMessage.1.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testDefaultUserMessageViewWithShortMessage.2.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testWithImageErrorResultForAgentWithoutTitleAndMessage.1.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testWithImageErrorResultForAgentWithoutTitleAndMessage.2.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testWithImageErrorResultForUser.1.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testWithImageErrorResultForUser.2.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testWithImageResultForAgentWithoutTitleAndMessage.1.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testWithImageResultForAgentWithoutTitleAndMessage.2.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testWithImageResultForUser.1.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testWithImageResultForUser.2.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testWithLoadingImageForAgentWithoutTitleAndMessage.1.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testWithLoadingImageForAgentWithoutTitleAndMessage.2.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testWithLoadingImageForUser.1.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testWithLoadingImageForUser.2.png
Labels: in progress, ready

#99 Work on ParleyTextView
  Sources/Parley/PropertyWrappers/ParleyScaledFont.swift
  Sources/Parley/Views/CollectionViewCells/MessageCollectionViewCell/MessageCollectionViewCell.swift
  Sources/Parley/Views/CollectionViewCells/MessageCollectionViewCell/MessageCollectionViewCellAppearance.swift
  Sources/Parley/Views/ParleyMessageView/ParleyMessageView.swift
  Sources/Parley/Views/ParleyMessageView/ParleyMessageViewAppearance.swift
  Sources/Parley/Views/ParleyStickyView/ParleyStickyView.swift
  Sources/Parley/Views/ParleyStickyView/ParleyStickyViewAppearance.swift
  Sources/Parley/Views/ParleyTextView.swift
  Sources/Parley/Views/ParleyTextView/ParleyTextView.swift
  Sources/Parley/Views/ParleyTextView/ParleyTextViewAppearance.swift
  Sources/Parley/Views/ParleyViewAppearance.swift
  Sources/Parley/Views/TableViewCells/InfoTableViewCell/InfoTableViewCell.swift
  Sources/Parley/Views/TableViewCells/InfoTableViewCell/InfoTableViewCellAppearance.swift
  Sources/Parley/Views/TableViewCells/MessageTableViewCell/MessageTableViewCellAppearance.swift
  Tests/ParleyTests/ParleyTextViewTests.swift
  Tests/ParleyTests/__Snapshots__/ParleyTextViewTests/testBoldTextWithDefaultStyle.1.png
  Tests/ParleyTests/__Snapshots__/ParleyTextViewTests/testCombinationOfBoldAndItalicAndLinkStyleWithNonDefaultStyle.1.png
  Tests/ParleyTests/__Snapshots__/ParleyTextViewTests/testDynamicFontScalingDefaultStyle.1.png
  Tests/ParleyTests/__Snapshots__/ParleyTextViewTests/testItalicTextWithDefaultStyle.1.png
  Tests/ParleyTests/__Snapshots__/ParleyTextViewTests/testNormalTextWithDefaultStyle.1.png
  Tests/ParleyTests/__Snapshots__/ParleyTextViewTests/testTextIsMultining.1.png
  Tests/ParleyTests/__Snapshots__/ParleyTextViewTests/testTextWithLinkWithDefaultStyle.1.png
Labels: enhancement, ready

#101 Add new certificate for 2024 -> 2025
  CHANGELOG.md
  Example/ParleyExample.xcodeproj/project.pbxproj
  Example/ParleyExample/Supporting Files/_.parley.nu_27-May-2024.cer
  Example/ParleyExample/Supporting Files/_.parley.nu_29-Jul-2023.cer
  README.md
Labels: ready

#102 Bugfix/image viewer
  CHANGELOG.md
  Sources/Parley/Views/MessageImageViewController.swift
Labels: ready

#110 Feature/fix image name label not scaling dynamic font size
  Sources/Parley/Views/ParleyMessageView/ParleyMessageView.swift
  Tests/ParleyTests/Media.xcassets/white_image.imageset/Contents.json
  Tests/ParleyTests/Media.xcassets/white_image.imageset/white_image.png
  Tests/ParleyTests/ParleyMessageViewTests.swift
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testCustomBalloonImageUser.1.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testCustomBalloonImageUser.2.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testDefaultAgentMessageView.1.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testDefaultAgentMessageView.2.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testDefaultAgentMessageViewWithShortMessage.1.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testDefaultAgentMessageViewWithShortMessage.2.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testDefaultUserMessageView.1.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testDefaultUserMessageView.2.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testDefaultUserMessageViewFailedStatus.1.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testDefaultUserMessageViewFailedStatus.2.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testDefaultUserMessageViewPendingStatus.1.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testDefaultUserMessageViewPendingStatus.2.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testDefaultUserMessageViewWithShortMessage.1.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testDefaultUserMessageViewWithShortMessage.2.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testWithImageErrorResultForAgentWithoutTitleAndMessage.1.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testWithImageErrorResultForAgentWithoutTitleAndMessage.2.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testWithImageErrorResultForUser.1.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testWithImageErrorResultForUser.2.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testWithImageResultForAgentWithoutTitleAndMessage.1.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testWithImageResultForAgentWithoutTitleAndMessage.2.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testWithImageResultForUser.1.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testWithImageResultForUser.2.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testWithLoadingImageForAgentWithoutTitleAndMessage.1.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testWithLoadingImageForAgentWithoutTitleAndMessage.2.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testWithLoadingImageForUser.1.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testWithLoadingImageForUser.2.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testWithWhiteImageResultForAgentWithoutTitleAndMessage.1.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testWithWhiteImageResultForAgentWithoutTitleAndMessage.2.png
Labels: bug, ready

#106 Create ci step to build code on pr;
  .github/dependabot.yml
  .github/workflows/swift-validate.yml
Labels: ready

#112 Add new function to remove all local user data;
  Sources/Parley/Parley.swift
Labels: enhancement, ready

#113 #95 Make possible to configure custom localization.
  Sources/Parley/Config/ApiVersion.swift
  Sources/Parley/Config/Constants.swift
  Sources/Parley/Config/ParleyNetworkConfig.swift
  Sources/Parley/Data/Localization/LocalizationManager.swift
  Sources/Parley/Data/Localization/ParleyLocalizationKey.swift
  Sources/Parley/Data/Localization/ParleyLocalizationManager.swift
  Sources/Parley/Data/Models/AccesssibilityHelpers/MessageAccessibility.swift
  Sources/Parley/Data/Models/ParleyErrorResponse/NotificationErrors/MediaUploadNotificationErrorKind.swift
  Sources/Parley/Data/NotificationService.swift
  Sources/Parley/Data/PollingService.swift
  Sources/Parley/Data/Remotes/MessageTypeEvent.swift
  Sources/Parley/Extensions/Data+append.swift
  Sources/Parley/Extensions/ErrorExtension.swift
  Sources/Parley/Extensions/StringExtension.swift
  Sources/Parley/Parley.swift
  Sources/Parley/Views/MessageImageViewController.swift
  Sources/Parley/Views/ParleyComposeView/ParleyComposeView.swift
  Sources/Parley/Views/ParleyView.swift
  Tests/ParleyTests/ParleyTests.swift
  Tests/ParleyTests/TestDoubles/LocalizationManagerSpy.swift
Labels: enhancement, ready

#116 Bugfix/detail image not always loading
  Sources/Parley/Views/MessageImageViewController.swift
  Sources/Parley/Views/ParleyMessageView/ParleyMessageView.swift
  Sources/Parley/Views/ParleyMessageView/ParleyMessageViewDelegate.swift
  Sources/Parley/Views/ParleyTextView/ParleyTextView.swift
  Sources/Parley/Views/ParleyView.swift
  Tests/ParleyTests/ParleyMessageViewTests.swift
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testCustomBalloonImageUser.1.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testCustomBalloonImageUser.2.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testDefaultAgentMessageView.1.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testDefaultAgentMessageView.2.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testDefaultAgentMessageViewWithShortMessage.1.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testDefaultAgentMessageViewWithShortMessage.2.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testDefaultUserMessageView.1.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testDefaultUserMessageView.2.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testDefaultUserMessageViewFailedStatus.1.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testDefaultUserMessageViewFailedStatus.2.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testDefaultUserMessageViewPendingStatus.1.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testDefaultUserMessageViewPendingStatus.2.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testDefaultUserMessageViewWithShortMessage.1.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testDefaultUserMessageViewWithShortMessage.2.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testWithImageErrorResultForAgentWithoutTitleAndMessage.1.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testWithImageErrorResultForAgentWithoutTitleAndMessage.2.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testWithImageErrorResultForUser.1.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testWithImageErrorResultForUser.2.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testWithImageResultForAgentWithoutTitleAndMessage.1.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testWithImageResultForAgentWithoutTitleAndMessage.2.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testWithImageResultForUser.1.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testWithImageResultForUser.2.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testWithLoadingImageForAgentWithoutTitleAndMessage.1.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testWithLoadingImageForAgentWithoutTitleAndMessage.2.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testWithLoadingImageForUser.1.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testWithLoadingImageForUser.2.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testWithWhiteImageResultForAgentWithoutTitleAndMessage.1.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testWithWhiteImageResultForAgentWithoutTitleAndMessage.2.png
  Tests/ParleyTests/__Snapshots__/ParleyTextViewTests/testCombinationOfBoldAndItalicAndLinkStyleWithNonDefaultStyle.1.png
  Tests/ParleyTests/__Snapshots__/ParleyTextViewTests/testDynamicFontScalingDefaultStyle.1.png
Labels: bug, ready

#120 Fixed gradients not rendering correctly while loading image.
  Sources/Parley/Views/ParleyMessageView/ParleyMessageView.swift
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testWithImageErrorResultForAgentWithoutTitleAndMessage.1.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testWithImageErrorResultForAgentWithoutTitleAndMessage.2.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testWithImageErrorResultForUser.1.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testWithImageErrorResultForUser.2.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testWithImageResultForAgentWithoutTitleAndMessage.1.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testWithImageResultForAgentWithoutTitleAndMessage.2.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testWithImageResultForUser.1.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testWithImageResultForUser.2.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testWithLoadingImageForUser.1.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testWithLoadingImageForUser.2.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testWithWhiteImageResultForAgentWithoutTitleAndMessage.1.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testWithWhiteImageResultForAgentWithoutTitleAndMessage.2.png
Labels: bug, ready

#121 Bugfix/agent meta
  Sources/Parley/Views/ParleyMessageView/ParleyMessageView.xib
  Tests/ParleyTests/ParleyMessageViewTests.swift
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testCustomBalloonImageUser.1.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testCustomBalloonImageUser.2.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testDefaultAgentMessageView.1.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testDefaultAgentMessageView.2.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testDefaultAgentMessageViewWithShortMessage.1.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testDefaultAgentMessageViewWithShortMessage.2.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testDefaultUserMessageView.1.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testDefaultUserMessageView.2.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testDefaultUserMessageViewFailedStatus.1.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testDefaultUserMessageViewFailedStatus.2.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testDefaultUserMessageViewPendingStatus.1.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testDefaultUserMessageViewPendingStatus.2.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testDefaultUserMessageViewWithShortMessage.1.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testDefaultUserMessageViewWithShortMessage.2.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testWithImageErrorResultForAgentWithoutTitleAndMessage.1.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testWithImageErrorResultForAgentWithoutTitleAndMessage.2.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testWithImageErrorResultForUser.1.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testWithImageErrorResultForUser.2.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testWithImageResultForAgentWithoutTitleAndMessage.1.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testWithImageResultForAgentWithoutTitleAndMessage.2.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testWithImageResultForUser.1.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testWithImageResultForUser.2.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testWithLoadingImageForAgentWithoutTitleAndMessage.1.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testWithLoadingImageForUser.1.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testWithLoadingImageForUser.2.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testWithWhiteImageResultForAgentWithoutTitleAndMessage.1.png
  Tests/ParleyTests/__Snapshots__/ParleyMessageViewTests/testWithWhiteImageResultForAgentWithoutTitleAndMessage.2.png
Labels: bug, ready
